name: Build FoxFlake binary cache and update flake locks 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-foxflake-binary-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "stable", "stable-test", "unstable", "unstable-test", "dev" ]
    steps:
      - name: Reclaim disk space
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - name: Display disk space
        run: |
          echo "Free space:"
          df -h
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Install cachix action
        uses: cachix/cachix-action@v16
        with:
          name: foxflake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build FoxFlake binary cache
        run: |
           exit 0
#          ./create_binary_cache.sh ${{ matrix.branch }}
      - name: Test
        run: |
          echo "Fetch workflow run jobs"
          json_data=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")
          echo ${json_data}
          exit 1
      - name: Upload updated FoxFlake flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-${{ matrix.branch }}-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-${{ matrix.branch }}-flake.lock
          if-no-files-found: error
  update-foxflake-flake-locks:
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "stable", "stable-test", "unstable","unstable-test","dev" ]
    steps:
      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Download FoxFlake ${{ matrix.branch }} flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-${{ matrix.branch }}-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake ${{ matrix.branch }} flake lock
        run: |
          cp ./foxflake-${{ matrix.branch }}-flake.lock ./flake.lock
          rm ./foxflake-${{ matrix.branch }}-flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ matrix.branch }}
          commit_message: Update flake lock
