name: Build FoxFlake binary cache and update flake locks 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-foxflake-binary-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "stable", "stable-test", "unstable", "unstable-test", "dev" ]
    steps:
      - name: Reclaim disk space
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - name: Display disk space
        run: |
          echo "Free space:"
          df -h
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Initialize matrix lock
        if: matrix.branch == 'stable'
        uses: rakles/matrix-lock@v1.0.0
        with:
          step: init
          order: "stable,stable-test,unstable,unstable-test,dev"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Install cachix action
        uses: cachix/cachix-action@v16
        with:
          name: foxflake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build FoxFlake binary cache
        run: |
          ./create_binary_cache.sh ${{ matrix.branch }}
      - name: Wait for matrix lock
        uses: rakles/matrix-lock@v1.0.0
        with:
          step: wait
          id: ${{ matrix.branch }}
      - name: Upload updated FoxFlake flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-${{ matrix.branch }}-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-${{ matrix.branch }}-flake.lock
          if-no-files-found: error
      - name: Continue matrix lock
        uses: rakles/matrix-lock@v1.0.0
        with:
          step: continue
          id: ${{ matrix.branch }}
  update-foxflake-flake-locks:
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "stable", "stable-test", "unstable","unstable-test","dev" ]
    steps:
      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Download FoxFlake ${{ matrix.branch }} flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-${{ matrix.branch }}-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake ${{ matrix.branch }} flake lock
        run: |
          cp ./foxflake-${{ matrix.branch }}-flake.lock ./flake.lock
          rm ./foxflake-${{ matrix.branch }}-flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ matrix.branch }}
          commit_message: Update flake lock
