name: Build FoxFlake binary cache and update flake locks 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-foxflake-binary-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim disk space
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - name: Display disk space
        run: |
          echo "Free space:"
          df -h
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Install cachix action
        uses: cachix/cachix-action@v16
        with:
          name: foxflake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build FoxFlake binary cache
        run: |
          ./create_binary_cache.sh
      - name: Upload FoxFlake stable flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-stable-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-stable-flake.lock
          if-no-files-found: error
      - name: Upload FoxFlake stable test flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-stable-test-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-stable-test-flake.lock
          if-no-files-found: error
      - name: Upload FoxFlake unstable flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-unstable-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-unstable-flake.lock
          if-no-files-found: error
      - name: Upload FoxFlake unstable test flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-unstable-test-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-unstable-test-flake.lock
          if-no-files-found: error
      - name: Upload FoxFlake dev flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: foxflake-dev-flake-lock
          path: /home/runner/work/foxflake/foxflake/foxflake-dev-flake.lock
          if-no-files-found: error
  update-foxflake-stable-flake-lock:
    runs-on: ubuntu-latest
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    steps:
      - name: Checkout stable branch
        uses: actions/checkout@v4
        with:
          ref: stable
      - name: Download FoxFlake stable flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-stable-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake stable flake lock
        run: cp /home/runner/work/foxflake/foxflake/foxflake-stable-flake.lock ./flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: stable
          commit_message: Update flake lock
  update-foxflake-stable-test-flake-lock:
    runs-on: ubuntu-latest
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    steps:
      - name: Checkout stable test branch
        uses: actions/checkout@v4
        with:
          ref: stable-test
      - name: Download FoxFlake stable test flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-stable-test-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake stable test flake lock
        run: cp /home/runner/work/foxflake/foxflake/foxflake-stable-test-flake.lock ./flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: stable-test
          commit_message: Update flake lock
  update-foxflake-unstable-flake-lock:
    runs-on: ubuntu-latest
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    steps:
      - name: Checkout unstable branch
        uses: actions/checkout@v4
        with:
          ref: unstable
      - name: Download FoxFlake unstable flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-unstable-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake unstable flake lock
        run: cp /home/runner/work/foxflake/foxflake/foxflake-unstable-flake.lock ./flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: unstable
          commit_message: Update flake lock
  update-foxflake-unstable-test-flake-lock:
    runs-on: ubuntu-latest
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    steps:
      - name: Checkout unstable test branch
        uses: actions/checkout@v4
        with:
          ref: unstable-test
      - name: Download FoxFlake unstable test flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-unstable-test-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake unstable test flake lock
        run: cp /home/runner/work/foxflake/foxflake/foxflake-unstable-test-flake.lock ./flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: unstable-test
          commit_message: Update flake lock
  update-foxflake-dev-flake-lock:
    runs-on: ubuntu-latest
    needs: create-foxflake-binary-cache
    permissions:
      contents: write
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Download FoxFlake dev flake lock
        uses: actions/download-artifact@v4
        with:
          name: foxflake-dev-flake-lock
          path: /home/runner/work/foxflake/foxflake/
      - name: Copy FoxFlake dev flake lock
        run: cp /home/runner/work/foxflake/foxflake/foxflake-dev-flake.lock ./flake.lock
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: dev
          commit_message: Update flake lock
