name: "Update flake lock dev"
on:
  workflow_dispatch:
jobs:
  update-flake-locks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: Install nix
      uses: cachix/install-nix-action@v31
    - name: Update flake lock
      run: |
        nix flake update --flake .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update flake lock
